### YamlMime:FAQ
metadata:
  title: グループに割り当てられている Azure AD ロールのトラブルシューティング - Azure Active Directory
  description: Azure Active Directory のグループにロールを割り当てる際の一般的な質問とトラブルシューティングのヒントをいくつか紹介します。
  services: active-directory
  author: rolyon
  manager: daveba
  ms.service: active-directory
  ms.workload: identity
  ms.subservice: roles
  ms.topic: article
  ms.date: 11/05/2020
  ms.author: rolyon
  ms.reviewer: vincesm
  ms.custom: it-pro
  ms.collection: M365-identity-device-management
  ms.openlocfilehash: c09bcdde3713f3ab93814cc67b23ded5cc49c17d
  ms.sourcegitcommit: 106f5c9fa5c6d3498dd1cfe63181a7ed4125ae6d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 11/02/2021
  ms.locfileid: "131057136"
title: グループに割り当てられている Azure AD ロールをトラブルシューティングする
summary: ここでは、Azure AD グループへの Azure Active Directory (Azure AD) ロールの割り当てに関する一般的な質問とトラブルシューティングのヒントについて説明します。
sections:
- name: 無視
  questions:
  - question: >
      グループ管理者ですが、[グループに Azure AD ロールを割り当てることができる] スイッチが表示されません。
    answer: >
      特権ロール管理者かグローバル管理者のみが、ロールの割り当ての対象となるグループを作成できます。 これらのロールのユーザーにのみ、このコントロールは表示されます。
  - question: >
      Azure AD ロールに割り当てられているグループのメンバーシップは、誰が変更できますか?
    answer: >
      既定では、ロールを割り当て可能なグループのメンバーシップを管理するのは特権ロール管理者とグローバル管理者のみですが、グループ所有者を追加して、ロールを割り当て可能なグループの管理を委任することができます。
  - question: >
      組織のヘルプデスク管理者ですが、ディレクトリ閲覧者であるユーザーのパスワードを更新できません。 なぜですか?
    answer: >
      そのユーザーは、ロールを割り当て可能なグループ経由でディレクトリ閲覧者となった可能性があります。 ロールを割り当て可能なグループのすべてのメンバーと所有者は保護されています。 特権認証管理者または全体管理者のロールのユーザーのみが、保護されたユーザーの資格情報をリセットできます。
  - question: >
      あるユーザーのパスワードを更新できません。 そのユーザーには、高い特権ロールは一切割り当てられていません。 更新できないのはなぜですか?
    answer: "そのユーザーは、ロールを割り当て可能なグループの所有者である可能性があります。 特権の昇格を避けるため、ロールを割り当て可能なグループの所有者は保護されています。 たとえば、Contoso_Security_Admins というグループがセキュリティ管理者ロールに割り当てられており、Bob がそのグループの所有者で、Alice は組織内のパスワード管理者であるとします。 この保護が存在しないとすれば、Alice が Bob の資格情報をリセットして、Bob の ID を引き継ぐことが可能になります。 そうなると、Alice は自身や他のユーザーを Contoso_Security_Admins グループに追加して、その組織のセキュリティ管理者になることができてしまいます。 あるユーザーがグループの所有者であるかどうかを確認するには、そのユーザーの所有オブジェクトの一覧を取得し、そのグループのいずれかで isAssignableToRole が true に設定されているかどうかを確認します。 設定されている場合、そのユーザーは保護対象であり、この動作は仕様によるものです。 所有オブジェクトの取得については、次のドキュメントを参照してください。\n\n- [Get-AzureADUserOwnedObject](/powershell/module/azuread/get-azureaduserownedobject)  \n- [List ownedObjects](/graph/api/user-list-ownedobjects?tabs=http)\n"
  - question: "Azure AD ロールに割り当てることができるグループ (具体的には、isAssignableToRole プロパティが true に設定されているグループ) にアクセス レビューを作成できますか?  \n"
    answer: >
      はい、できます。 グローバル管理者と特権ロール管理者だけが、ロール割り当て可能なグループを作成できます。
  - question: >
      アクセス パッケージを作成して、Azure AD ロールに割り当てることができるグループをその中に配置することはできますか?
    answer: "はい、できます。 グローバル管理者とユーザー管理者には、任意のグループをアクセス パッケージに配置する権限があります。 グローバル管理者には何も変更はありませんが、ユーザー管理者ロールのアクセス許可には若干の変更が加えられています。 ロールを割り当て可能なグループをアクセス パッケージに配置するには、ユーザー管理者であると同時に、ロールを割り当て可能なそのグループの所有者でもある必要があります。 エンタープライズ ライセンス管理でアクセス パッケージを作成できるユーザーの完全な表を次に示します。\n\nAzure AD ディレクトリ ロール | エンタイトルメント管理ロール | セキュリティ グループの追加\\* | Microsoft 365 グループの追加\\* | アプリの追加 | SharePoint Online サイトの追加\n----------------------- | --------------------------- | ----------------------- | ------------------------- | ----------- |  -----------------------------\nグローバル管理者 | 該当なし | ✔️ | ✔️ | ✔️  | ✔️\nユーザー管理者  | 該当なし  | ✔️  | ✔️  | ✔️\nIntune 管理者 | カタログ所有者 | ✔️  | ✔️  | &nbsp;  | &nbsp;\nExchange 管理者  | カタログ所有者  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nTeams サービス管理者 | カタログ所有者  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nSharePoint 管理者 | カタログ所有者 | &nbsp; | ✔️  | &nbsp;  | ✔️ \nアプリケーション管理者 | カタログ所有者  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nクラウドアプリケーション管理者 | カタログ所有者  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nUser | カタログ所有者 | グループ所有者の場合のみ | グループ所有者の場合のみ | アプリ所有者の場合のみ  | &nbsp;\n\n\\*グループはロールを割り当て可能ではありません。つまり、isAssignableToRole = false です。 グループがロールを割り当て可能な場合は、アクセス パッケージを作成するユーザーは、ロールを割り当て可能なそのグループの所有者でもある必要があります。\n"
  - question: >
      [割り当てられたロール] に [割り当ての削除] オプションが見つかりません。 ユーザーへのロールの割り当てをどうすれば削除できますか?
    answer: >
      この回答は、Azure AD Premium P1 組織にのみ適用されます。


      1. [Azure portal](https://portal.azure.com)または [Azure AD 管理センター](https://aad.portal.azure.com)にサインインし、 **Azure Active Directory** を開きます。

      1. ユーザーを選択して、ユーザー プロファイルを開きます。

      1. **[割り当てられたロール]** を選択します。

      1. 歯車アイコンを選択します。 この情報を提供するペインが開きます。 直接割り当ての横に [削除] ボタンがあります。 間接的なロールの割り当てを削除するには、そのロールに割り当てられているグループからユーザーを削除します。
  - question: >
      ロールを割り当て可能なすべてのグループを表示するにはどうすればよいですか?
    answer: >
      次の手順に従います。


      1. [Azure portal](https://portal.azure.com)または [Azure AD 管理センター](https://aad.portal.azure.com)にサインインし、 **Azure Active Directory** を開きます。

      1. **[グループ]**  >  **[すべてのグループ]** の順に選択します。

      1. **[フィルターの追加]** を選択します。

      1. **[ロールを割り当て可能]** でフィルター処理を実行します。
  - question: >
      プリンシパルに直接または間接的に割り当てられているロールを確認するにはどうすればよいですか?
    answer: >
      次の手順に従います。


      1. [Azure portal](https://portal.azure.com)または [Azure AD 管理センター](https://aad.portal.azure.com)にサインインし、 **Azure Active Directory** を開きます。

      1. ユーザーを選択して、ユーザー プロファイルを開きます。

      1. **[割り当てられたロール]** を選択し、次の操作を実行します。

          - Azure AD Premium P1 ライセンスを持つ組織の場合:歯車アイコンを選択します。 この情報を提供するペインが開きます。
          - Azure AD Premium P2 ライセンスを持つ組織の場合:直接および継承されたライセンス情報は、 **[メンバーシップ]** 列に表示されます。
  - question: "役割に割り当てるための新しいグループを作成する必要があるのはなぜですか。  \n"
    answer: >
      既存のグループをロールに割り当てると、その既存のグループの所有者がこのグループに他のメンバーを追加し、それらの新しいメンバーが自分はロールを持つことになるということを認識しない事態が起こり得ます。 ロールを割り当て可能なグループは強力なので、それを保護するために多くの制限が設けられています。 グループを管理しているユーザーが驚くような変更をグループに加えることは望ましくありません。
additionalContent: "\n## <a name=\"next-steps\"></a>次のステップ\n\n- [Azure AD グループを使用してロールの割り当てを管理する](groups-concept.md)\n- [ロールを割り当て可能なグループを作成する](groups-create-eligible.md)"
