### YamlMime:FAQ
metadata:
  title: Application Gateway の Azure Web アプリケーション ファイアウォール - よく寄せられる質問
  description: この記事では、Application Gateway の Web アプリケーション ファイアウォールに関してよく寄せられる質問の回答を示します
  services: web-application-firewall
  author: vhorne
  ms.service: web-application-firewall
  ms.topic: article
  ms.date: 05/05/2020
  ms.author: victorh
  ms.openlocfilehash: d7d5d5c9ea2c0af4933a7bff50ab310d95d29741
  ms.sourcegitcommit: c05e595b9f2dbe78e657fed2eb75c8fe511610e7
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 06/11/2021
  ms.locfileid: "112034891"
title: Application Gateway の Azure Web アプリケーション ファイアウォールに関してよく寄せられる質問
summary: この記事では、Application Gateway の Azure Web アプリケーション ファイアウォール (WAF) 機能に関する一般的な質問に回答します。
sections:
- name: 無視
  questions:
  - question: >
      Azure WAF とは何ですか?
    answer: >
      Azure WAF は Web アプリケーション ファイアウォールです。SQL インジェクション、クロスサイト スクリプティング、その他の Web エクスプロイトなどの一般的な脅威から Web アプリケーションを保護するのに役立ちます。 Web アプリケーションへのアクセスを制御するために、カスタム ルールとマネージド ルールの組み合わせからなる WAF ポリシーを定義できます。


      Azure WAF ポリシーは、Application Gateway または Azure Front Door でホストされている Web アプリケーションに適用できます。
  - question: >
      WAF SKU はどのような機能でサポートされていますか。
    answer: >
      WAF SKU では、Standard SKU で利用可能なすべての機能がサポートされています。
  - question: >
      WAF を監視するにはどうすればよいですか?
    answer: >
      WAF の監視には、診断ログを使用します。 詳細については、[Application Gateway の診断ログとメトリック](../../application-gateway/application-gateway-diagnostics.md)に関するページを参照してください。
  - question: >
      検出モードではトラフィックがブロックされますか?
    answer: >
      いいえ。 検出モードでは、WAF 規則をトリガーするトラフィックをログに記録するにとどまります。
  - question: >
      WAF ルールはカスタマイズできますか?
    answer: >
      はい。 詳細については、[WAF 規則グループと規則のカスタマイズ](application-gateway-customize-waf-rules-portal.md)に関するページを参照してください。
  - question: >
      WAF で現在利用できるのはどのような規則ですか?
    answer: "WAF で現在サポートされているのは、CRS [2.2.9](application-gateway-crs-rulegroups-rules.md#owasp229)、[3.0](application-gateway-crs-rulegroups-rules.md#owasp30)、および [3.1](application-gateway-crs-rulegroups-rules.md#owasp31) です。 これらの規則は、Open Web Application Security Project (OWASP) が特定した 10 の脆弱性のほとんどに対するベースライン セキュリティを提供するものです。 \n\n* SQL インジェクションからの保護\n* クロスサイト スクリプティングに対する保護\n* 一般的な Web 攻撃 (コマンド インジェクション、HTTP 要求スマグリング、HTTP 応答スプリッティング、リモート ファイル インクルード攻撃など) に対する保護\n* HTTP プロトコル違反に対する保護\n* HTTP プロトコル異常に対する保護 (ホスト ユーザー エージェントと承認ヘッダーが見つからない場合など)\n* ボット、クローラー、スキャナーの防止\n* アプリケーションのよくある構成ミスの検出 (Apache、IIS など)\n\n詳細については、[OWASP の 10 の脆弱性](https://owasp.org/www-project-top-ten/)に関するページを参照してください。\n"
  - question: >
      WAF はどのようなコンテンツ タイプをサポートしていますか。
    answer: >
      Application Gateway WAF は、次のコンテンツ タイプをサポートしています (マネージド ルールの場合)。


      * application/json

      * application/xml

      * application/x-www-form-urlencoded

      * multipart/form-data


      カスタム ルールの場合:


      * application/x-www-form-urlencoded

      * multipart/form-data
  - question: >
      WAF は DDoS 保護をサポートしていますか?
    answer: >
      はい。 アプリケーション ゲートウェイをデプロイしてある仮想ネットワーク上で、DDos 保護を有効にすることができます。 この設定によって、アプリケーション ゲートウェイの仮想 IP (VIP) も Azure DDoS Protection サービスによる保護の対象になります。


      ### <a name="does-waf-store-customer-data"></a>WAF は顧客データを格納しますか?


      いいえ。WAF は顧客データを格納しません。
additionalContent: "\n## <a name=\"next-steps\"></a>次のステップ\n\n- [Azure Web アプリケーション ファイアウォール](../overview.md)について学習します。\n- [Azure Front Door](../../frontdoor/front-door-overview.md) の詳細を確認します。"
